apiVersion: v1
kind: Service
metadata:
  name: visa-ml-service
  namespace: visa-system
spec:
  selector:
    app: visa-ml-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
